import fs from 'node:fs';
import path from 'node:path';
import {randomUUID} from 'node:crypto';

const quote = value => "'" + value.replaceAll("'", "'\\''") + "'";
const fail = () => {throw new Error('command_install_conflict');};
function ownedDirectory(dir) {
  const stat = fs.lstatSync(dir);
  if (!stat.isDirectory() || stat.uid !== process.getuid() || (stat.mode & 0o022) || fs.realpathSync(dir) !== dir) fail();
}
/** Install a textual launcher, never overwrite a foreign or modified command.
 * The launcher pins this installed entrypoint and the Node used for init.
 * Existing Go installations and shell startup files remain untouched. */
export function installCommand({installRoot, home, nodePath = process.execPath, replace = false, previousInstallRoot, previousNodePath = nodePath}) {
  for (const value of [installRoot, home, nodePath]) {
    if (typeof value !== 'string' || !path.isAbsolute(value) || /[\x00-\x1f\x7f]/.test(value)) fail();
  }
  ownedDirectory(home);
  const entry = fs.lstatSync(path.join(installRoot, 'packages/task-local/main.ts'));
  if (!entry.isFile() || entry.uid !== process.getuid() || (entry.mode & 0o022)) fail();
  let directory = home;
  for (const part of ['.local', 'bin']) {
    directory = path.join(directory, part);
    try {fs.mkdirSync(directory, {mode: 0o700});} catch (error) {if (error.code !== 'EEXIST') throw error;}
    ownedDirectory(directory);
  }
  const commandPath = path.join(directory, 'marshal');
  const render = (node, root) => `#!/bin/sh\n# Marshal Node launcher; generated by marshal init.\nexec ${quote(node)} ${quote(path.join(root, 'packages/task-local/main.ts'))} "$@"\n`;
  const content = render(nodePath, installRoot);
  let fd;
  try {fd = fs.openSync(commandPath, 'wx', 0o755);} catch (error) {
    if (error.code !== 'EEXIST') throw error;
    const existing = fs.openSync(commandPath, fs.constants.O_RDONLY | fs.constants.O_NOFOLLOW | fs.constants.O_NONBLOCK);
    try {
      const stat = fs.fstatSync(existing);
      if (!stat.isFile() || stat.uid !== process.getuid() || stat.nlink !== 1 || (stat.mode & 0o022) || !(stat.mode & 0o100) || stat.size > 16384) fail();
      const buffer = Buffer.alloc(stat.size + 1);
      const n = fs.readSync(existing, buffer, 0, buffer.length, 0);
      const actual = buffer.subarray(0, n).toString();
      if (actual === content) return {commandPath, created: false};
      if (!replace || ![previousInstallRoot, previousNodePath].every(value => typeof value === 'string' && path.isAbsolute(value) &&
        !/[\x00-\x1f\x7f]/.test(value)) || actual !== render(previousNodePath, previousInstallRoot)) fail();
      const temporary = path.join(directory, `.marshal-launcher-${process.pid}-${randomUUID()}`);
      let pending;
      try {
        pending = fs.openSync(temporary, 'wx', 0o755);
        fs.writeFileSync(pending, content); fs.fsyncSync(pending); fs.closeSync(pending); pending = undefined;
        ownedDirectory(directory);
        const current = fs.lstatSync(commandPath), held = fs.fstatSync(existing);
        if (!current.isFile() || current.dev !== stat.dev || current.ino !== stat.ino || current.nlink !== 1 ||
          current.size !== stat.size || current.mtimeMs !== stat.mtimeMs || current.ctimeMs !== stat.ctimeMs ||
          held.size !== stat.size || held.mtimeMs !== stat.mtimeMs || held.ctimeMs !== stat.ctimeMs) fail();
        fs.renameSync(temporary, commandPath);
        const dirFd = fs.openSync(directory, fs.constants.O_RDONLY | fs.constants.O_DIRECTORY | fs.constants.O_NOFOLLOW);
        try {fs.fsyncSync(dirFd);} finally {fs.closeSync(dirFd);}
        return {commandPath, created: false, replaced: true};
      } finally {
        if (pending !== undefined) fs.closeSync(pending);
        if (fs.existsSync(temporary)) fs.unlinkSync(temporary);
      }
    } finally {fs.closeSync(existing);}
  }
  try {fs.writeFileSync(fd, content); fs.fsyncSync(fd);} finally {fs.closeSync(fd);}
  return {commandPath, created: true};
}
