import fs from 'node:fs';
import path from 'node:path';

const quote = value => "'" + value.replaceAll("'", "'\\''") + "'";
const fail = () => {throw new Error('command_install_conflict');};
function ownedDirectory(dir) {
  const stat = fs.lstatSync(dir);
  if (!stat.isDirectory() || stat.uid !== process.getuid() || (stat.mode & 0o022) || fs.realpathSync(dir) !== dir) fail();
}
/** Install a textual launcher, never overwrite a foreign or modified command.
 * The launcher pins this installed entrypoint and the Node used for init.
 * Existing Go installations and shell startup files remain untouched. */
export function installCommand({installRoot, home, nodePath = process.execPath}) {
  for (const value of [installRoot, home, nodePath]) {
    if (typeof value !== 'string' || !path.isAbsolute(value) || /[\x00-\x1f\x7f]/.test(value)) fail();
  }
  ownedDirectory(home);
  const entry = fs.lstatSync(path.join(installRoot, 'packages/task-local/main.mjs'));
  if (!entry.isFile() || entry.uid !== process.getuid() || (entry.mode & 0o022)) fail();
  let directory = home;
  for (const part of ['.local', 'bin']) {
    directory = path.join(directory, part);
    try {fs.mkdirSync(directory, {mode: 0o700});} catch (error) {if (error.code !== 'EEXIST') throw error;}
    ownedDirectory(directory);
  }
  const commandPath = path.join(directory, 'marshal');
  const content = `#!/bin/sh\n# Marshal Node launcher; generated by marshal init.\nexec ${quote(nodePath)} ${quote(path.join(installRoot, 'packages/task-local/main.mjs'))} "$@"\n`;
  let fd;
  try {fd = fs.openSync(commandPath, 'wx', 0o755);} catch (error) {
    if (error.code !== 'EEXIST') throw error;
    const existing = fs.openSync(commandPath, fs.constants.O_RDONLY | fs.constants.O_NOFOLLOW | fs.constants.O_NONBLOCK);
    try {
      const stat = fs.fstatSync(existing);
      if (!stat.isFile() || stat.uid !== process.getuid() || (stat.mode & 0o022) || !(stat.mode & 0o100) || stat.size !== Buffer.byteLength(content)) fail();
      const buffer = Buffer.alloc(Buffer.byteLength(content) + 1);
      const n = fs.readSync(existing, buffer, 0, buffer.length, 0);
      if (buffer.subarray(0, n).toString() !== content) fail();
      return {commandPath, created: false};
    } finally {fs.closeSync(existing);}
  }
  try {fs.writeFileSync(fd, content); fs.fsyncSync(fd);} finally {fs.closeSync(fd);}
  return {commandPath, created: true};
}
