import test from 'node:test';import assert from 'node:assert/strict';
import {parseAssessmentLeaderProposal,renderAssessmentReviewPrompt,createGenericFilesReviewWireConfig} from './review-wire.ts';
import {assessmentFixture,assessmentProposal} from '../task-application/review-assessment.fixture.ts';
import {reviewCriteria,parseAssessmentProposal} from '../task-application/review-assessment-contract.ts';
import {reviewAssessmentPolicy,startReviewWithAssessments,reviewAssessmentEvidence} from '../task-application/review-assessment.ts';
import {receipt} from '../task-application/leader-ports.ts';
import {encode,digest} from '../task-store/store.ts';
import {validate} from '../task-api/contract.ts';
const hash=x=>digest(encode(x));
test('受信mapper仅在计划批准前附加条目，其他动作原样保留',()=>{
 const ticket={executionType:'leader',input:{leader:{profile:'task-managed-leader/v1',callId:'call',inputDigest:hash('input')}}};
 const proposal={acceptance:['业务原文'],nodes:[]},wire={profile:'generic-files-leader-proposal/v1',summary:'计划',actions:[{type:'plan',proposal}]};
 const parse=()=>parseAssessmentLeaderProposal({ticket,completion:{outputText:JSON.stringify(wire)}});
 const report=parse();assert.equal(proposal.acceptance.length,1);assert.equal(report.actions[0].proposal.acceptance[0],'业务原文');
 assert.equal(reviewCriteria({...report.actions[0].proposal,digest:hash('plan')}).length,5);
 wire.actions=[{type:'conclude',outcome:'wait',summary:'待回答',basisDigests:[]}];assert.equal(encode(parse().actions).toString(),encode(wire.actions).toString());
});
test('真实Core输入可渲染、只调用一次原Provider、获得绑定v2证据及Schema格式',async t=>{
 const f=await assessmentFixture(t),ticket={...f.reviewTicket,providerId:'controlled'},input=ticket.input.review;
 const raw=assessmentProposal(ticket),prompt=renderAssessmentReviewPrompt(input);
 assert.ok(prompt.endsWith(encode(input).toString()));assert.equal(prompt.split('\n完整冻结输入：').length,2);
 assert.ok(Buffer.byteLength(prompt)<262144);
 let calls=0;const started={executionId:'controlled',startedAt:new Date().toISOString()};
 const provider={id:'controlled',start(){calls++;return {started:Promise.resolve(started),stop(){},completion:Promise.resolve({providerId:'controlled',status:'completed',stopReason:'end_turn',outputText:JSON.stringify(raw),cleanup:{started,cleaned:true}})};}};
 const config=createGenericFilesReviewWireConfig({provider,assessmentContract:'task-review-assessment/v1'});
 assert.equal(reviewAssessmentPolicy(config.review).profile,'task-review-assessment/v1');
 assert.equal(reviewAssessmentPolicy(createGenericFilesReviewWireConfig({provider}).review),null);
 const result=await startReviewWithAssessments(config.review,{ticket,provider,prepared:{prompt}}).completion;
 const report=receipt(config.review,ticket,result).value,assessment=reviewAssessmentEvidence(config.review,ticket,result);
 assert.equal(calls,1);assert.deepEqual(assessment,parseAssessmentProposal({ticket,completion:{outputText:JSON.stringify(raw)}}).assessment);
 const envelope={profile:'task-independent-review/v2',ticketDigest:hash(ticket),report,assessment};
 assert.equal(validate(envelope,'ReviewEvidenceEnvelope'),true);
 for(const [name,value] of [['ReviewAssessment',assessment],['ReviewCriteriaItem',assessment.criteria[0]],['ReviewEvidenceSource',assessment.sources[0]],['ReviewAssessmentCheck',assessment.checks[0]]])assert.equal(validate(value,name),true,name);
 assert.equal(validate({...envelope,extra:1},'ReviewEvidenceEnvelope'),false);
});
