import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {execFileSync, spawnSync} from 'node:child_process';
import {createHash} from 'node:crypto';
import {pack, verify, restoreCarrier, SOURCE_FILES} from './index.mjs';

const repository = fs.realpathSync(fileURLToPath(new URL('../..', import.meta.url)));
const cli = fileURLToPath(new URL('./main.mjs', import.meta.url));
const sha = value => 'sha256:' + createHash('sha256').update(value).digest('hex');
const git = (cwd, ...args) => execFileSync('git', ['-C', cwd, ...args], {encoding: 'utf8', timeout: 10000, stdio: ['ignore', 'pipe', 'pipe']}).trim();
function fixture(t) {
  const parent = fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(), 'marshal-carrier-')));
  t.after(() => fs.rmSync(parent, {recursive: true, force: true}));
  const source = path.join(parent, 'source'), carrier = path.join(parent, 'carrier'), target = path.join(parent, 'installed');
  fs.mkdirSync(source, {mode: 0o700});
  for (const file of SOURCE_FILES) {
    fs.mkdirSync(path.dirname(path.join(source, file)), {mode: 0o700, recursive: true});
    fs.copyFileSync(path.join(repository, file), path.join(source, file));
  }
  git(source, 'init', '-q'); git(source, 'add', 'packages');
  git(source, '-c', 'user.name=Fixture', '-c', 'user.email=fixture@example.invalid', '-c', 'commit.gpgsign=false', 'commit', '-qm', 'carrier fixture source');
  const sourceHead = git(source, 'rev-parse', 'HEAD'), report = pack({sourceRoot: source, sourceHead, target: carrier});
  // Reproduce directory-artifact transport mode normalization. No content,
  // original manifest or expected pin is generated by the consumer.
  function transported(directory) {
    fs.chmodSync(directory, 0o755);
    for (const entry of fs.readdirSync(directory, {withFileTypes: true})) {
      const file = path.join(directory, entry.name);
      if (entry.isDirectory()) transported(file); else fs.chmodSync(file, 0o644);
    }
  }
  transported(carrier);
  const options = {carrier, target, sourceHead, manifestDigest: report.manifestDigest};
  return {parent, source, carrier, target, report, options, restore: () => restoreCarrier(options)};
}
function untouched(f, work) {assert.throws(work); assert.equal(fs.existsSync(f.target), false, 'reject before any install target is created');}

test('one transported package restores identical bytes twice under the current non-root owner without Git or repack', t => {
  const f = fixture(t); assert.ok(process.getuid() > 0);
  assert.throws(() => verify({root: f.carrier, manifestDigest: f.report.manifestDigest}), /unsafe_permissions/);
  const original = new Map([...SOURCE_FILES, 'manifest.json'].map(file => [file, fs.readFileSync(path.join(f.carrier, file))]));
  // The producer checkout is unavailable and PATH cannot find Git. Only the
  // independently supplied pin and carrier bytes remain to this CLI consumer.
  fs.renameSync(f.source, f.source + '-not-a-consumer-input');
  const restored = spawnSync(process.execPath, [cli, 'restore-carrier', '--carrier', f.carrier, '--target', f.target,
    '--manifest-digest', f.report.manifestDigest, '--source-head', f.options.sourceHead], {env: {PATH: '/not-a-git-path'}, timeout: 10000, encoding: 'utf8'});
  assert.equal(restored.status, 0, restored.stderr); assert.equal(restored.stderr, '');
  const report = JSON.parse(restored.stdout);
  assert.equal(report.sourceHead, f.options.sourceHead); assert.equal(report.manifestDigest, f.report.manifestDigest);
  assert.deepEqual(restoreCarrier({...f.options, target: path.join(f.parent, 'second')}), report);
  assert.deepEqual(verify({root: f.target, manifestDigest: report.manifestDigest}), report);
  assert.equal(fs.statSync(f.target).mode & 0o7777, 0o700); assert.equal(fs.statSync(f.target).uid, process.getuid());
  for (const [file, bytes] of original) {
    assert.deepEqual(fs.readFileSync(path.join(f.target, file)), bytes);
    assert.deepEqual(fs.readFileSync(path.join(f.carrier, file)), bytes);
    assert.equal(fs.statSync(path.join(f.target, file)).mode & 0o7777, 0o600);
    assert.equal(fs.statSync(path.join(f.target, file)).uid, process.getuid());
    assert.equal(fs.statSync(path.join(f.carrier, file)).mode & 0o7777, 0o644, 'carrier was not chmodded');
  }
});

test('missing or mismatched external pins/source identities fail before target creation', t => {
  const f = fixture(t);
  for (const change of [{manifestDigest: undefined}, {manifestDigest: 'sha256:' + '0'.repeat(64)},
    {sourceHead: '0'.repeat(40)}, {sourceHead: undefined}]) untouched(f, () => restoreCarrier({...f.options, ...change}));
  const manifestFile = path.join(f.carrier, 'manifest.json'), bytes = fs.readFileSync(manifestFile);
  const value = JSON.parse(bytes); value.files[0].path = '../escape.mjs';
  const malicious = Buffer.from(JSON.stringify(value, null, 2) + '\n'); fs.writeFileSync(manifestFile, malicious);
  untouched(f, f.restore); // The original external pin cannot be replaced by a carrier claim.
  untouched(f, () => restoreCarrier({...f.options, manifestDigest: sha(malicious)})); // Even an explicit pin cannot broaden the source inventory.
});

test('extra, missing, changed and oversized carrier bytes cannot be copied or executed', t => {
  const f = fixture(t), file = path.join(f.carrier, SOURCE_FILES[0]), bytes = fs.readFileSync(file);
  const extra = path.join(f.carrier, 'not-in-manifest');
  fs.writeFileSync(extra, 'do not read or execute'); untouched(f, f.restore); fs.unlinkSync(extra);
  fs.mkdirSync(extra); untouched(f, f.restore); fs.rmdirSync(extra);
  fs.unlinkSync(file); untouched(f, f.restore);
  fs.writeFileSync(file, bytes.subarray(1)); untouched(f, f.restore);
  fs.writeFileSync(file, Buffer.alloc(2 * 1024 * 1024 + 1)); untouched(f, f.restore);
  fs.writeFileSync(file, bytes);
  fs.writeFileSync(path.join(f.carrier, 'manifest.json'), Buffer.alloc(65537)); untouched(f, f.restore);
  // Opening a special manifest must fail immediately, not wait for a writer.
  const manifest = path.join(f.carrier, 'manifest.json'); fs.unlinkSync(manifest);
  execFileSync('/usr/bin/mkfifo', [manifest], {timeout: 3000});
  const fifo = spawnSync(process.execPath, [cli, 'restore-carrier', '--carrier', f.carrier, '--target', f.target,
    '--manifest-digest', f.report.manifestDigest, '--source-head', f.options.sourceHead], {encoding: 'utf8', timeout: 3000});
  assert.equal(fifo.status, 1); assert.equal(fifo.signal, null); assert.equal(fifo.error, undefined);
  assert.deepEqual(JSON.parse(fifo.stderr), {code: 'unsafe_file'}); assert.equal(fs.existsSync(f.target), false);
});

test('carrier links, aliases and hardlinks are rejected without touching the outside target', t => {
  const f = fixture(t), file = path.join(f.carrier, SOURCE_FILES[0]), bytes = fs.readFileSync(file), outside = path.join(f.parent, 'outside');
  fs.writeFileSync(outside, 'outside sentinel'); fs.unlinkSync(file); fs.symlinkSync(outside, file);
  untouched(f, f.restore); assert.equal(fs.readFileSync(outside, 'utf8'), 'outside sentinel'); fs.unlinkSync(file);
  fs.linkSync(outside, file); untouched(f, f.restore); fs.unlinkSync(file); fs.writeFileSync(file, bytes);
  const alias = path.join(f.parent, 'carrier-alias'); fs.symlinkSync(f.carrier, alias);
  untouched(f, () => restoreCarrier({...f.options, carrier: alias}));
  fs.symlinkSync(f.parent, path.join(f.carrier, 'linked-directory')); untouched(f, f.restore);
});

test('existing targets and unsafe parents are never adopted, repaired or overwritten', t => {
  const f = fixture(t);
  fs.mkdirSync(f.target, {mode: 0o700}); const marker = path.join(f.target, 'keep'); fs.writeFileSync(marker, 'keep');
  assert.throws(f.restore); assert.equal(fs.readFileSync(marker, 'utf8'), 'keep');
  assert.throws(() => restoreCarrier({...f.options, target: path.join(f.carrier, 'nested')}), /invalid_target/);
  assert.equal(fs.existsSync(path.join(f.carrier, 'nested')), false);
  const wide = path.join(f.parent, 'wide'); fs.mkdirSync(wide, {mode: 0o755});
  assert.throws(() => restoreCarrier({...f.options, target: path.join(wide, 'installed')}), /unsafe_target/);
  assert.equal(fs.existsSync(path.join(wide, 'installed')), false); assert.equal(fs.statSync(wide).mode & 0o777, 0o755);
  const alias = path.join(f.parent, 'parent-alias'); fs.symlinkSync(f.parent, alias);
  assert.throws(() => restoreCarrier({...f.options, target: path.join(alias, 'alias-target')}), /unsafe_directory/);
  assert.equal(fs.existsSync(path.join(f.parent, 'alias-target')), false);
});

test('file or parent sync failure preserves the fresh target and never returns success or reuses it', t => {
  const f = fixture(t), original = fs.fsyncSync;
  for (const stage of ['file', 'parent']) {
    const target = path.join(f.parent, stage), attempted = [];
    try {
      fs.fsyncSync = fd => {
        const stat = fs.fstatSync(fd); attempted.push(stat.ino);
        if (stage === 'file' && stat.isFile() || stage === 'parent' && stat.ino === fs.statSync(f.parent).ino) throw Error('injected-sync-failure');
        original(fd);
      };
      assert.throws(() => restoreCarrier({...f.options, target}), /package_io_failed/);
    } finally {fs.fsyncSync = original;}
    assert.ok(attempted.length); assert.ok(fs.existsSync(target));
    const file = path.join(target, SOURCE_FILES[0]), bytes = fs.readFileSync(file);
    assert.throws(() => restoreCarrier({...f.options, target})); assert.deepEqual(fs.readFileSync(file), bytes);
  }
});

test('held installation parent replacement is detected before returning a usable package', t => {
  const f = fixture(t), parent = path.join(f.parent, 'private-parent'); fs.mkdirSync(parent, {mode: 0o700});
  const target = path.join(parent, 'package'), identity = fs.statSync(parent).ino, original = fs.fsyncSync; let replaced = false;
  try {
    fs.fsyncSync = fd => {
      original(fd);
      if (!replaced && fs.fstatSync(fd).ino === identity) {replaced = true; fs.renameSync(parent, parent + '-old'); fs.mkdirSync(parent, {mode: 0o700});}
    };
    assert.throws(() => restoreCarrier({...f.options, target}), /unsafe_target/);
  } finally {fs.fsyncSync = original;}
  assert.equal(replaced, true); assert.deepEqual(fs.readdirSync(parent), []);
});

test('explicit candidate consumer rejects absent inputs rather than packing its checkout', () => {
  const entry = fileURLToPath(new URL('./candidate-consumer.mjs', import.meta.url));
  const result = spawnSync(process.execPath, [entry], {env: {}, encoding: 'utf8', timeout: 10000});
  assert.notEqual(result.status, 0); assert.doesNotMatch(result.stdout, /"originalExecutions"/);
  const consumer = fs.readFileSync(entry, 'utf8') + fs.readFileSync(fileURLToPath(new URL('./installed-team.fixture.mjs', import.meta.url)), 'utf8');
  assert.doesNotMatch(consumer, /\bpack\s*\(|\bexecFileSync\b|\bgit\s*\(/);
});
